spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL:localhost}:5432/kata-db
    username: ${DATASOURCE_USER:admin}
    password: ${DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

  security:
    user:
      name: client1
      password: 1234

axon:
  eventhandling:
    processors:
      order-group:
        mode: subscribing
