name: Delivery CI build

on:
  workflow_run:
    workflows: [ "Delivery CI build" ]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Run test
        run: mvn test
      - name: Build
        run: mvn -D skipTests package --file pom.xml
      - name: Publish package
        run: mvn jar:jar deploy:deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}